name: CD

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  integration:
    uses: xjb/workflow_example/.github/workflows/ci.yml@main

  build:
    needs:
      - integration

    runs-on: ubuntu-latest

    steps:
      - run: exit 0

  deploy:
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - run: exit 0
