name: CI

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  workflow_call:

jobs:
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: exit 0

  lint-css:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: exit 1

  lint-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: exit 0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: exit 0
