name: Create JSON

on:
  workflow_dispatch:

jobs:
  action-set-json-field:
    runs-on: ubuntu-latest
    steps:
      - run: echo {} > my-file.json
      - uses: jossef/action-set-json-field@v2.1
        with:
          file: my-file.json
          field: description
          value: my custom data
      - run: cat my-file.json

  create-json:
    runs-on: ubuntu-latest
    steps:
      - uses: jsdaniell/create-json@v1.2.2
        with:
          name: "new-json-file.json"
          json: '{"name":"jsdaniell", "password":"mypass"}'
      - run: cat new-json-file.json

  variable-substitution:
    runs-on: ubuntu-latest
    steps:
      - run: echo '{"name":"", "password":""}' > msvs.json
      - uses: microsoft/variable-substitution@v1 
        with:
          files: msvs.json
        env:
          name: jsdaniell
          password: mypass
      - run: cat msvs.json
