name: Create JSON

on:
  workflow_dispatch:

jobs:
  json:
    runs-on: ubuntu-latest
    steps:
      - uses: jossef/action-set-json-field@v2.1
        with:
          file: my-file.json
          field: description
          value: my custom data
